version: '3.5'

services:
  login:
    build:
      context: .
      dockerfile: Dockerfile
    image: login_service
    container_name: login_service
    ports:
      - "9091:9091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka