version: '3.5'

services:
  payment_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment_service
    container_name: payment_service
    ports: 
      - "9095:9095"
    environment: 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka
