version: '3.5'

services:
  order:
    build:
      context: .
      dockerfile: Dockerfile
    image: order_service
    container_name: order_service
    ports:
      - "9094:9094"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://host.docker.internal:8761/eureka